### ISSUE TITLE
Simulation race condition in frontend.v

### ISSUE THREAD

**Issue by chrmard** [Wren6991/Hazard3#21] opened 2024-09-19 11:17 UTC
For the fifo definition hazard3_frontend.v uses the same signals in a synchronous process (e.g. in fifo_update for `fifo_mem[0..FIFO_DEPTH-1]`) and an asynchronous process (e.g. boundary_conditions for `fifo_mem[FIFO_DEPTH]`).

From verilog language definition this is correct, and most simulator and synthesis have no issue with this.
I checked the code on some Verilator versions, they have a problem (for example Verilator 5.018 2023-10-30 rev v5.018). Cadence and Synopsys tools have not.

Observation on Verilator: The `fifo_valid` and `fifo_valid_m1` logic is not simulated over delta cycles, it is updated only once when the `fifo_mem` signal is processed.

To overcome this situation, the process can be split. It has no functional impact; it separates only the "shared async/sync signals" from the pure async signals. With this patch the Verilator problem is solved. Apply this patch would prevent other user to debug this tool issue again.

 ```
diff --git a/hdl/hazard3_frontend.v b/hdl/hazard3_frontend.v
index ac30c77..4f55585 100644
--- a/hdl/hazard3_frontend.v
+++ b/hdl/hazard3_frontend.v
@@ -131,11 +131,14 @@ wire              fifo_pop;
 wire              fifo_dbg_inject = DEBUG_SUPPORT && dbg_instr_data_vld && dbg_instr_data_rdy;
 
 always @ (*) begin: boundary_conditions
-       integer i;
        fifo_mem[FIFO_DEPTH] = mem_data;
        fifo_predbranch[FIFO_DEPTH] = 2'b00;
        fifo_err[FIFO_DEPTH] = 1'b0;
        fifo_valid_hw[FIFO_DEPTH] = 2'b00;
+end
+
+always @ (*) begin: fifo_valdidation
+       integer i;
        for (i = 0; i < FIFO_DEPTH; i = i + 1) begin
                fifo_valid[i] = |EXTENSION_C ? |fifo_valid_hw[i] : fifo_valid_hw[i][0];
                // valid-to-right condition: i == 0 || fifo_valid[i - 1], but without
```

There is one other linting problem in the same file. As verilog interpretes undefined signals as false in && condition, the behaviour is not impacted. The other usages of this signal are gated by BRANCH_PREDICTOR define itself.
```
@@ -224,6 +227,7 @@ if (BRANCH_PREDICTOR) begin: have_btb
 end else begin: no_btb
        always @ (*) begin
                btb_src_addr = {W_ADDR{1'b0}};
+               btb_src_size = 1'b0;
                btb_target_addr = {W_ADDR{1'b0}};
                btb_valid = 1'b0;
        end
```

**Comment by Arturron** [comment] 2024-09-19 11:18
try this

https://bit.ly/4eugCty
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Wren6991** [comment] 2024-12-01 14:52
As far as I can tell this is not a simulation race. There are multiple possible interleavings of events, but only one possible result.

I'll have a look at reproducing with that specific verilator version. I'm not sure I can take the suggested change as-is because it seems to introduce multiple sensitivities for different bits in the same packed array, and this is something other tools take issue with.

**Comment by laurentiuduca** [comment] 2024-12-03 12:21
hi, do you have a copy of hazard3 that works with verilator?
i am trying to simulate example_soc and no success even if it compiles without warnings

**Comment by Wren6991** [comment] 2024-12-09 04:47
Confirmed on verilator `rev v5.030-138-g965631152` (latest git `master`)

**Comment by Wren6991** [comment] 2024-12-09 04:56
So in your modified code there are three processes:

1. Combinatorial process for static tie-offs
1. Combinatorial process for actual combinatorial decode of meta-flags
1. Synchronous process for updating state flags

Without the modification, 1 + 2 are merged. There is something about `fifo_valid_hw` specifically (which is mostly synchronously updated, but has a static tie-off for a loop boundary condition) which is causing process 2 to not be scheduled correctly by Verilator. For example, this patch also avoids the issue:

```patch
diff --git a/hdl/hazard3_frontend.v b/hdl/hazard3_frontend.v
index d54a027..ec4b889 100644
--- a/hdl/hazard3_frontend.v
+++ b/hdl/hazard3_frontend.v
@@ -159,13 +159,16 @@ wire              fifo_pop;
 wire              fifo_dbg_inject = DEBUG_SUPPORT && dbg_instr_data_vld && dbg_instr_data_rdy;
 
 always @ (*) begin: boundary_conditions
+       fifo_valid_hw[FIFO_DEPTH] = 2'b00;
+end
+
+always @ (*) begin: fifo_validation
        integer i;
        fifo_mem[FIFO_DEPTH] = mem_data;
        fifo_predbranch[FIFO_DEPTH] = 2'b00;
        fifo_err[FIFO_DEPTH] = 1'b0;
        fifo_break_any[FIFO_DEPTH] = 2'b00;
        fifo_break_d_mode[FIFO_DEPTH] = 2'b00;
-       fifo_valid_hw[FIFO_DEPTH] = 2'b00;
        for (i = 0; i <= FIFO_DEPTH; i = i + 1) begin
                fifo_valid[i] = |EXTENSION_C ? |fifo_valid_hw[i] : fifo_valid_hw[i][0];
                // valid-to-right condition: i == 0 || fifo_valid[i - 1], but without
```

So does this:

```patch
diff --git a/hdl/hazard3_frontend.v b/hdl/hazard3_frontend.v
index d54a027..ee5f12a 100644
--- a/hdl/hazard3_frontend.v
+++ b/hdl/hazard3_frontend.v
@@ -165,7 +165,6 @@ always @ (*) begin: boundary_conditions
        fifo_err[FIFO_DEPTH] = 1'b0;
        fifo_break_any[FIFO_DEPTH] = 2'b00;
        fifo_break_d_mode[FIFO_DEPTH] = 2'b00;
-       fifo_valid_hw[FIFO_DEPTH] = 2'b00;
        for (i = 0; i <= FIFO_DEPTH; i = i + 1) begin
                fifo_valid[i] = |EXTENSION_C ? |fifo_valid_hw[i] : fifo_valid_hw[i][0];
                // valid-to-right condition: i == 0 || fifo_valid[i - 1], but without
@@ -191,6 +190,7 @@ always @ (posedge clk or negedge rst_n) begin: fifo_update
                        fifo_predbranch[i] <= 2'b00;
                end
        end else begin
+               fifo_valid_hw[FIFO_DEPTH] <= 2'b00;
                for (i = 0; i < FIFO_DEPTH; i = i + 1) begin
                        if (fifo_pop || (fifo_push && !fifo_valid[i])) begin
                                fifo_mem[i]          <= fifo_valid[i + 1] ? fifo_mem[i + 1]          : mem_data;
```

**Comment by Wren6991** [comment] 2024-12-09 05:10
Since this affects multiple Verilator versions I'll do a point release with just that last patch.

With that patch, I can run the basic tests in `test/sim/sw_testcases` with a port of the CXXRTL test harness.

**Closed as completed** 2024-12-09 05:55 UTC
